openapi: 3.0.0
info:
  title: Datalake - API publica de talento cloud
  description: >-
    API REST para entregar info a datalake.


    En la documentación se mencionan 2 urls:

    - Producción: https://[tenant].talento.cloud/

    - Pruebas: https://[tenant].talento-dev.cloud/


    El client_id y client_secret son suministrados por talento cloud al cliente.


    Maneja autenticación Oauth 2.0 y se podria consultar los siguientes informes en formato application/json:
      - HojaVida - Información de nómina - OK
      - HojaVida - Reporte datos básicos usuario interno - Pendiente
      - Selección - Reporte de selección detallado - Pendiente
      - Selección - Seguimiento por etapas - Pendiente
      - Formación - Avance por tema - Pendiente
      - Bienestar - reporte detallado beneficios/reconocimientos - Pendiente
      - Bienestar - reporte transacciones puntos beneficios/reconocimientos  - Pendiente    
      - Objetivos Smart - Resultados consolidados de gestión (Todo el grupo) - Pendiente
      - Objetivos Smart - Modelo mapa de desempeño - Pendiente
      - Competencias - Detalle valoración de competencias (de todo el grupo) - Pendiente
      - Operativos (Dec) - Reporte operativos - Pendiente
      - Transversal - Reporte de todos los usuarios del sistema - Pendiente
      - Transversal - Reporte de los usuarios activos - Pendiente
      - Transversal - Novedades - Pendiente

    ## Manejo de errores


        Los errores habituales pueden incluir:


        - `400 Bad Request`: Parámetros requeridos faltantes o con formato
        inválido.
            
        - `401 Unauthorized`: Token JWT inválido, expirado o ausente.
            
        - `403 Forbidden`: El usuario autenticado no tiene permisos suficientes.
            
        - `404 Not Found`: El recurso solicitado no existe.
            
        - `500 Internal Server Error`: Error inesperado en el servidor.
            

        Cuando sea posible, cada endpoint detallará sus códigos de error
        específicos y estructura de respuesta en su propia descripción. 
  contact: {}
  version: '1.0'
servers:
- url: https://somostalentoalianza.talento.cloud/api/html
  description: Servidor de producción     
- url: https://somostalentoalianza.talento-dev.cloud/api/html
  description: Servidor de pruebas
  variables: {}
paths:
  /oauth2/token/{tenant}.json:
    post:
      tags:
      - Datalake
      summary: OAuth2 - Obtener token      
      description: >-
        Para obtener el token que autoriza uso de los otros servicios, el client_id y client_secret son suministrados por talento cloud al cliente, según el tenant la url cambia, por ejemplo para la empresa Alianza sería https://somostalentoalianza.talento.cloud/api/html/oauth2/token/somostalentoalianza.json

        ## Ejemplo petición con curl:

        ```bash

        curl -X POST https://somostalentoalianza.talento.cloud/api/html/oauth2/token/somostalentoalianza.json \
          -H "Content-Type: application/x-www-form-urlencoded" \          
          -d "grant_type=client_credentials" \
          -d "client_id=webhook-servicio" \
          -d "client_secret=mi-secreto" \
          -d "scope=talento.read"

        ```

        ## Ejemplo uso token generado:

        ```bash

        curl -X POST https://somostalentoalianza.talento.cloud/api/v1/datalake/modulox/reportey  \
          -H "Authorization: Bearer eyJhbGci..."

        ```      
      x-codeSamples:
        - lang: Shell
          label: cURL
          source: |
            curl -X POST https://somostalentoalianza.talento.cloud/api/html/oauth2/token/somostalentoalianza.json \
              -H "Content-Type: application/x-www-form-urlencoded" \          
              -d "grant_type=client_credentials" \
              -d "client_id=webhook-servicio" \
              -d "client_secret=mi-secreto" \
              -d "scope=talento.read"
      operationId: OAuth2-Obtenertoken
      parameters:
      - name: tenant
        in: path
        required: true
        description: El tenant de la organización, y para la empresa Alianza sería somostalentoalianza
        schema:
          type: string
          example: somostalentoalianza
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - client_id
              - client_secret
              - grant_type
              - scope
              type: object
              properties:
                client_id:
                  type: string
                  example: 389f8c63f55d48aee6da5f7517db3dcf
                client_secret:
                  type: string
                  example: 7df40e8c97a1c2d689a11d3cb34d5e5bb8245d9074b1efcb02eda1ce05a190a6
                grant_type:
                  type: string
                  description: Por defecto client_credentials
                  example: client_credentials
                scope:
                  type: string
                  description: Por defecto talento.read
                  example: talento.read
        required: false
      responses:
        '200':
          description: OK
          headers:
            Content-Language:
              content:
                text/plain:
                  schema:
                    type: string
                  example: es-CO
          content:
            application/json;charset=UTF-8:
              schema:
                allOf:
                - $ref: '#/components/schemas/oauth2'
                - example:
                    acces_token: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ...
                    token_type: Bearer
                    expires_in: 900
                    success: true
                    scope: talento.write.candidato
              example:
                acces_token: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOi...
                token_type: Bearer
                expires_in: 900
                success: true
                scope: talento.write.candidato
      deprecated: false
      security: []
  /v1/datalake/hojavida/informacionNomina.json:
    get:
      tags:
      - Datalake
      summary: HojaVida - Información de nómina
      description: Endpoint donde se lista la información de nómina de las hojas de vida de usuarios activos de talento cloud. Las fechas se entregan en formato yyyy-mm-dd
      x-codeSamples:
        - lang: Shell
          label: cURL
          source: |
            curl --location 'https://somostalentoalianza.talento-dev.cloud/api/html/v1/datalake/hojavida/informacionNomina.json' \
              -H "Authorization: Bearer <TU_TOKEN_JWT>" 
      operationId: HojaVida-Informacióndenómina
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                allOf:
                - $ref: '#/components/schemas/HV_informacionNomina'
                - example:
                    data:
                    - usuario: ADRIANA PEREZ PEREZCORTES
                      tipo_documento: CEDULA
                      documento_usuario: '8587647000'
                      tipo_usuario: Administrativo
                      email: basura_talpostobon790@unmail.edu
                      negocio: Calidad de software
                      empresa: Soluciones Estratégicas Integrales para el Desarrollo Empresarial y Tecnológico S.A.S
                      uen: Nexa Digital Solutions
                      vicepresidencia: Financiera
                      pais: Colombia
                      ciudad: Cartagena
                      regional: Costa Atlántica
                      sede: Cartagena
                      cargo: Analista Desarrollador
                      nivel_organizacional: Analistas
                      area: TI
                      documento_jefe: '29498498195'
                      jefe: Alvaro Cardenas
                      fecha_ingreso: 2026-05-12
                      tipo_contrato: null
                      fecha_terminacion_contrato: null
                      forma_pago: null
                      tipo_salario: null
                      nomina: ''
                      regimen_pension: null
                      tipo_cuenta: null
                      banco: null
                      numero_cuenta: null
                      salario: null
                      cupo_beneficios: null
                      centros_costos: null
                      modalidad: null
                      labora_sabado: No
                      nombres_conceptos: null
                      valores_conceptos: null
                      corresponde_a_salario: null
                      eps: null
                      pension: null
                      cesantias: null
                      arl: ''
                      centro_trabajo_arl: ''
                      porcentaje_riesgo_arl: ''
                      lugar_expedicion: null
                      fecha_expedicion_documento: null
                      municipio_residencia: null
                      fecha_nacimiento_colaborador: null
                      ciudad_nacimiento: null
                      direccion: null
                      barrio: null
                      telefono: null
                      celular: null
                      correo: null
                      tipo_documento_beneficiario: null
                      documento_beneficiario: null
                      nombre_beneficiario: null
                      fecha_nacimiento: null
                      parentesco: null
                      ciudad_beneficiario: ''
                      relacion_seguridad_social: null
                      discapacidad: null
                      beneficiario_eps: null
                      beneficiario_caja_compensacion: null
                    - usuario: Alvaro Cardenas
                      tipo_documento: CEDULA
                      documento_usuario: '29498498195'
                      tipo_usuario: Administrativo
                      email: 360_360_360_prueba5@basura.com
                      negocio: Desarrollo de Software
                      empresa: Corporación Internacional de.
                      uen: UEN Desarrollo e innovación
                      vicepresidencia: TI
                      pais: Colombia
                      ciudad: Medellin
                      regional: Antioquia
                      sede: Medellín
                      cargo: Desarrollador Senior
                      nivel_organizacional: Analistas
                      area: TI
                      documento_jefe: '1117123456'
                      jefe: Andres Mauricio Jaramillo Salazar
                      fecha_ingreso: 2025-04-13
                      tipo_contrato: null
                      fecha_terminacion_contrato: null
                      forma_pago: null
                      tipo_salario: null
                      nomina: ''
                      regimen_pension: null
                      tipo_cuenta: null
                      banco: null
                      numero_cuenta: null
                      salario: null
                      cupo_beneficios: null
                      centros_costos: null
                      modalidad: null
                      labora_sabado: No
                      nombres_conceptos: null
                      valores_conceptos: null
                      corresponde_a_salario: null
                      eps: null
                      pension: null
                      cesantias: null
                      arl: ''
                      centro_trabajo_arl: ''
                      porcentaje_riesgo_arl: ''
                      lugar_expedicion: null
                      fecha_expedicion_documento: null
                      municipio_residencia: null
                      fecha_nacimiento_colaborador: null
                      ciudad_nacimiento: null
                      direccion: null
                      barrio: null
                      telefono: null
                      celular: null
                      correo: null
                      tipo_documento_beneficiario: null
                      documento_beneficiario: null
                      nombre_beneficiario: null
                      fecha_nacimiento: null
                      parentesco: null
                      ciudad_beneficiario: ''
                      relacion_seguridad_social: null
                      discapacidad: null
                      beneficiario_eps: null
                      beneficiario_caja_compensacion: null
                    - usuario: Amparo Echeverry
                      tipo_documento: CEDULA
                      documento_usuario: '29866304'
                      tipo_usuario: Administrativo
                      email: 353_353_353_text@gmail.com
                      negocio: Calidad de software
                      empresa: Nexa Solutions
                      uen: Nexa Digital Solutions
                      vicepresidencia: Gestión Humana
                      pais: Colombia
                      ciudad: Medellin
                      regional: Antioquia
                      sede: Medellín
                      cargo: Arquitecto TI
                      nivel_organizacional: Analistas
                      area: TI
                      documento_jefe: '42793011'
                      jefe: Deissy Echeverry Seleccion
                      fecha_ingreso: 2025-06-10
                      tipo_contrato: Contrato por prestación de servicios
                      fecha_terminacion_contrato: null
                      forma_pago: null
                      tipo_salario: null
                      nomina: ''
                      regimen_pension: null
                      tipo_cuenta: null
                      banco: null
                      numero_cuenta: ''
                      salario: '3200000'
                      cupo_beneficios: null
                      centros_costos: ''
                      modalidad: Casa
                      labora_sabado: No
                      nombres_conceptos: null
                      valores_conceptos: null
                      corresponde_a_salario: null
                      eps: null
                      pension: null
                      cesantias: null
                      arl: ''
                      centro_trabajo_arl: ''
                      porcentaje_riesgo_arl: ''
                      lugar_expedicion: ABINGDON DOWNS
                      fecha_expedicion_documento: 1989-01-10
                      municipio_residencia: AEROGLEN
                      fecha_nacimiento_colaborador: 1986-06-06
                      ciudad_nacimiento: ABINGDON DOWNS
                      direccion: 'Bulevar 55AD  # 66AC Este 66'
                      barrio: gyyyyy
                      telefono: '987564859680'
                      celular: '257372572'
                      correo: null
                      tipo_documento_beneficiario: null
                      documento_beneficiario: null
                      nombre_beneficiario: null
                      fecha_nacimiento: null
                      parentesco: null
                      ciudad_beneficiario: ''
                      relacion_seguridad_social: null
                      discapacidad: null
                      beneficiario_eps: null
                      beneficiario_caja_compensacion: null
                    - usuario: Ana Maria Gomez Ramirez
                      tipo_documento: CEDULA
                      documento_usuario: '43609065'
                      tipo_usuario: Administrativo
                      email: 238_xxxisrael.fonseca@talento.cloud
                      negocio: Desarrollo de Software
                      empresa: talento cloud
                      uen: UEN App Moviles
                      vicepresidencia: financiera
                      pais: Colombia
                      ciudad: Medellin
                      regional: Antioquia
                      sede: Medellín
                      cargo: Gerente de Calidad y Soporte
                      nivel_organizacional: Gerencial
                      area: Sistemas
                      documento_jefe: '21897678'
                      jefe: Blanca Ruiz Suarez
                      fecha_ingreso: 2022-11-29
                      tipo_contrato: Contrato a término indefinido
                      fecha_terminacion_contrato: null
                      forma_pago: null
                      tipo_salario: null
                      nomina: ''
                      regimen_pension: null
                      tipo_cuenta: Cuenta de ahorros
                      banco: Bancolombia
                      numero_cuenta: '650000005145'
                      salario: null
                      cupo_beneficios: null
                      centros_costos: ''
                      modalidad: Casa
                      labora_sabado: No
                      nombres_conceptos: null
                      valores_conceptos: null
                      corresponde_a_salario: null
                      eps: COMFAMILIAR DE NARIÑO EPS - CCF
                      pension: Colfondos
                      cesantias: Protección S.A
                      arl: ARL Positiva
                      centro_trabajo_arl: ''
                      porcentaje_riesgo_arl: ''
                      lugar_expedicion: Ricaurte
                      fecha_expedicion_documento: null
                      municipio_residencia: null
                      fecha_nacimiento_colaborador: null
                      ciudad_nacimiento: null
                      direccion: ''
                      barrio: ''
                      telefono: null
                      celular: 3215554444xxx
                      correo: null
                      tipo_documento_beneficiario: null
                      documento_beneficiario: null
                      nombre_beneficiario: null
                      fecha_nacimiento: null
                      parentesco: null
                      ciudad_beneficiario: ''
                      relacion_seguridad_social: null
                      discapacidad: null
                      beneficiario_eps: null
                      beneficiario_caja_compensacion: null
                    success: true
              example:
                data:
                - usuario: ADRIANA PEREZ PEREZCORTES
                  tipo_documento: CEDULA
                  documento_usuario: '8587647000'
                  tipo_usuario: Administrativo
                  email: basura_talpostobon790@unmail.edu
                  negocio: Calidad de software
                  empresa: Soluciones Estratégicas Integrales para el Desarrollo Empresarial y Tecnológico S.A.S
                  uen: Nexa Digital Solutions
                  vicepresidencia: Financiera
                  pais: Colombia
                  ciudad: Cartagena
                  regional: Costa Atlántica
                  sede: Cartagena
                  cargo: Analista Desarrollador
                  nivel_organizacional: Analistas
                  area: TI
                  documento_jefe: '29498498195'
                  jefe: Alvaro Cardenas
                  fecha_ingreso: 2026-05-12
                  tipo_contrato: null
                  fecha_terminacion_contrato: null
                  forma_pago: null
                  tipo_salario: null
                  nomina: ''
                  regimen_pension: null
                  tipo_cuenta: null
                  banco: null
                  numero_cuenta: null
                  salario: null
                  cupo_beneficios: null
                  centros_costos: null
                  modalidad: null
                  labora_sabado: No
                  nombres_conceptos: null
                  valores_conceptos: null
                  corresponde_a_salario: null
                  eps: null
                  pension: null
                  cesantias: null
                  arl: ''
                  centro_trabajo_arl: ''
                  porcentaje_riesgo_arl: ''
                  lugar_expedicion: null
                  fecha_expedicion_documento: null
                  municipio_residencia: null
                  fecha_nacimiento_colaborador: null
                  ciudad_nacimiento: null
                  direccion: null
                  barrio: null
                  telefono: null
                  celular: null
                  correo: null
                  tipo_documento_beneficiario: null
                  documento_beneficiario: null
                  nombre_beneficiario: null
                  fecha_nacimiento: null
                  parentesco: null
                  ciudad_beneficiario: ''
                  relacion_seguridad_social: null
                  discapacidad: null
                  beneficiario_eps: null
                  beneficiario_caja_compensacion: null
                - usuario: Alvaro Cardenas
                  tipo_documento: CEDULA
                  documento_usuario: '29498498195'
                  tipo_usuario: Administrativo
                  email: 360_360_360_prueba5@basura.com
                  negocio: Desarrollo de Software
                  empresa: Corporación Internacional de.
                  uen: UEN Desarrollo e innovación
                  vicepresidencia: TI
                  pais: Colombia
                  ciudad: Medellin
                  regional: Antioquia
                  sede: Medellín
                  cargo: Desarrollador Senior
                  nivel_organizacional: Analistas
                  area: TI
                  documento_jefe: '1117123456'
                  jefe: Andres Mauricio Jaramillo Salazar
                  fecha_ingreso: 2025-04-13
                  tipo_contrato: null
                  fecha_terminacion_contrato: null
                  forma_pago: null
                  tipo_salario: null
                  nomina: ''
                  regimen_pension: null
                  tipo_cuenta: null
                  banco: null
                  numero_cuenta: null
                  salario: null
                  cupo_beneficios: null
                  centros_costos: null
                  modalidad: null
                  labora_sabado: No
                  nombres_conceptos: null
                  valores_conceptos: null
                  corresponde_a_salario: null
                  eps: null
                  pension: null
                  cesantias: null
                  arl: ''
                  centro_trabajo_arl: ''
                  porcentaje_riesgo_arl: ''
                  lugar_expedicion: null
                  fecha_expedicion_documento: null
                  municipio_residencia: null
                  fecha_nacimiento_colaborador: null
                  ciudad_nacimiento: null
                  direccion: null
                  barrio: null
                  telefono: null
                  celular: null
                  correo: null
                  tipo_documento_beneficiario: null
                  documento_beneficiario: null
                  nombre_beneficiario: null
                  fecha_nacimiento: null
                  parentesco: null
                  ciudad_beneficiario: ''
                  relacion_seguridad_social: null
                  discapacidad: null
                  beneficiario_eps: null
                  beneficiario_caja_compensacion: null
                - usuario: Amparo Echeverry
                  tipo_documento: CEDULA
                  documento_usuario: '29866304'
                  tipo_usuario: Administrativo
                  email: 353_353_353_text@gmail.com
                  negocio: Calidad de software
                  empresa: Nexa Solutions
                  uen: Nexa Digital Solutions
                  vicepresidencia: Gestión Humana
                  pais: Colombia
                  ciudad: Medellin
                  regional: Antioquia
                  sede: Medellín
                  cargo: Arquitecto TI
                  nivel_organizacional: Analistas
                  area: TI
                  documento_jefe: '42793011'
                  jefe: Deissy Echeverry Seleccion
                  fecha_ingreso: 2025-06-10
                  tipo_contrato: Contrato por prestación de servicios
                  fecha_terminacion_contrato: null
                  forma_pago: null
                  tipo_salario: null
                  nomina: ''
                  regimen_pension: null
                  tipo_cuenta: null
                  banco: null
                  numero_cuenta: ''
                  salario: '3200000'
                  cupo_beneficios: null
                  centros_costos: ''
                  modalidad: Casa
                  labora_sabado: No
                  nombres_conceptos: null
                  valores_conceptos: null
                  corresponde_a_salario: null
                  eps: null
                  pension: null
                  cesantias: null
                  arl: ''
                  centro_trabajo_arl: ''
                  porcentaje_riesgo_arl: ''
                  lugar_expedicion: ABINGDON DOWNS
                  fecha_expedicion_documento: 1989-01-10
                  municipio_residencia: AEROGLEN
                  fecha_nacimiento_colaborador: 1986-06-06
                  ciudad_nacimiento: ABINGDON DOWNS
                  direccion: 'Bulevar 55AD  # 66AC Este 66'
                  barrio: gyyyyy
                  telefono: '987564859680'
                  celular: '257372572'
                  correo: null
                  tipo_documento_beneficiario: null
                  documento_beneficiario: null
                  nombre_beneficiario: null
                  fecha_nacimiento: null
                  parentesco: null
                  ciudad_beneficiario: ''
                  relacion_seguridad_social: null
                  discapacidad: null
                  beneficiario_eps: null
                  beneficiario_caja_compensacion: null
                - usuario: Ana Maria Gomez Ramirez
                  tipo_documento: CEDULA
                  documento_usuario: '43609065'
                  tipo_usuario: Administrativo
                  email: 238_xxxisrael.fonseca@talento.cloud
                  negocio: Desarrollo de Software
                  empresa: talento cloud
                  uen: UEN App Moviles
                  vicepresidencia: financiera
                  pais: Colombia
                  ciudad: Medellin
                  regional: Antioquia
                  sede: Medellín
                  cargo: Gerente de Calidad y Soporte
                  nivel_organizacional: Gerencial
                  area: Sistemas
                  documento_jefe: '21897678'
                  jefe: Blanca Ruiz Suarez
                  fecha_ingreso: 2022-11-29
                  tipo_contrato: Contrato a término indefinido
                  fecha_terminacion_contrato: null
                  forma_pago: null
                  tipo_salario: null
                  nomina: ''
                  regimen_pension: null
                  tipo_cuenta: Cuenta de ahorros
                  banco: Bancolombia
                  numero_cuenta: '650000005145'
                  salario: null
                  cupo_beneficios: null
                  centros_costos: ''
                  modalidad: Casa
                  labora_sabado: No
                  nombres_conceptos: null
                  valores_conceptos: null
                  corresponde_a_salario: null
                  eps: COMFAMILIAR DE NARIÑO EPS - CCF
                  pension: Colfondos
                  cesantias: Protección S.A
                  arl: ARL Positiva
                  centro_trabajo_arl: ''
                  porcentaje_riesgo_arl: ''
                  lugar_expedicion: Ricaurte
                  fecha_expedicion_documento: null
                  municipio_residencia: null
                  fecha_nacimiento_colaborador: null
                  ciudad_nacimiento: null
                  direccion: ''
                  barrio: ''
                  telefono: null
                  celular: 3215554444xxx
                  correo: null
                  tipo_documento_beneficiario: null
                  documento_beneficiario: null
                  nombre_beneficiario: null
                  fecha_nacimiento: null
                  parentesco: null
                  ciudad_beneficiario: ''
                  relacion_seguridad_social: null
                  discapacidad: null
                  beneficiario_eps: null
                  beneficiario_caja_compensacion: null
                success: true
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'        
      deprecated: false
components:
  schemas:
    oauth2:
      title: oauth2
      required:
      - acces_token
      - token_type
      - expires_in
      - success
      - scope
      type: object
      properties:
        acces_token:
          type: string
        token_type:
          type: string
        expires_in:
          type: integer
          format: int32
        success:
          type: boolean
        scope:
          type: string
      example:
        acces_token: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0YWxlbnRvLndyaXRlLmNhbmRpZGF0b3w5N2I3ZmY3OTYxMzhkZmFmZDA2YjY4MjA0YWQ3NmI2ZCIsInVzZXJJZCI6IjM0Iiwicm9sZSI6IldFQlNFUlZJQ0UiLCJleHBpcmUiOiIxNzc0MzgwNzU2NDQ1IiwiZW1wcmVzYSI6InRhbGVudG9fZGVtbyIsImxuZyI6ImVzIiwianRpIjoiNDE4MDM0ZjctMTQ1ZS00ZGQ2LTk4ZjMtYzc1YWMyMmI3YTIzIiwiaWF0IjoxNzc0Mzc5ODU3fQ.u4y60HfGC8sv3ZmFNZRSSO0-9grdxvWrjzZBA2f2dcXQReNHv5mubvjRUdDSu-Y4
        token_type: Bearer
        expires_in: 900
        success: true
        scope: talento.write.candidato
    HV_informacionNomina:
      title: HV_informacionNomina
      required:
      - data
      - success
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Datum'
          description: ''
        success:
          type: boolean
      example:
        data:
        - usuario: ADRIANA PEREZ PEREZCORTES
          tipo_documento: CEDULA
          documento_usuario: '8587647000'
          tipo_usuario: Administrativo
          email: basura_talpostobon790@unmail.edu
          negocio: Calidad de software
          empresa: Soluciones Estratégicas Integrales para el Desarrollo Empresarial y Tecnológico S.A.S
          uen: Nexa Digital Solutions
          vicepresidencia: Financiera
          pais: Colombia
          ciudad: Cartagena
          regional: Costa Atlántica
          sede: Cartagena
          cargo: Analista Desarrollador
          nivel_organizacional: Analistas
          area: TI
          documento_jefe: '29498498195'
          jefe: Alvaro Cardenas
          fecha_ingreso: 2026-05-12
          tipo_contrato: null
          fecha_terminacion_contrato: null
          forma_pago: null
          tipo_salario: null
          nomina: ''
          regimen_pension: null
          tipo_cuenta: null
          banco: null
          numero_cuenta: null
          salario: null
          cupo_beneficios: null
          centros_costos: null
          modalidad: null
          labora_sabado: No
          nombres_conceptos: null
          valores_conceptos: null
          corresponde_a_salario: null
          eps: null
          pension: null
          cesantias: null
          arl: ''
          centro_trabajo_arl: ''
          porcentaje_riesgo_arl: ''
          lugar_expedicion: null
          fecha_expedicion_documento: null
          municipio_residencia: null
          fecha_nacimiento_colaborador: null
          ciudad_nacimiento: null
          direccion: null
          barrio: null
          telefono: null
          celular: null
          correo: null
          tipo_documento_beneficiario: null
          documento_beneficiario: null
          nombre_beneficiario: null
          fecha_nacimiento: null
          parentesco: null
          ciudad_beneficiario: ''
          relacion_seguridad_social: null
          discapacidad: null
          beneficiario_eps: null
          beneficiario_caja_compensacion: null
        - usuario: Alvaro Cardenas
          tipo_documento: CEDULA
          documento_usuario: '29498498195'
          tipo_usuario: Administrativo
          email: 360_360_360_prueba5@basura.com
          negocio: Desarrollo de Software
          empresa: Corporación Internacional de.
          uen: UEN Desarrollo e innovación
          vicepresidencia: TI
          pais: Colombia
          ciudad: Medellin
          regional: Antioquia
          sede: Medellín
          cargo: Desarrollador Senior
          nivel_organizacional: Analistas
          area: TI
          documento_jefe: '1117123456'
          jefe: Andres Mauricio Jaramillo Salazar
          fecha_ingreso: 2025-04-13
          tipo_contrato: null
          fecha_terminacion_contrato: null
          forma_pago: null
          tipo_salario: null
          nomina: ''
          regimen_pension: null
          tipo_cuenta: null
          banco: null
          numero_cuenta: null
          salario: null
          cupo_beneficios: null
          centros_costos: null
          modalidad: null
          labora_sabado: No
          nombres_conceptos: null
          valores_conceptos: null
          corresponde_a_salario: null
          eps: null
          pension: null
          cesantias: null
          arl: ''
          centro_trabajo_arl: ''
          porcentaje_riesgo_arl: ''
          lugar_expedicion: null
          fecha_expedicion_documento: null
          municipio_residencia: null
          fecha_nacimiento_colaborador: null
          ciudad_nacimiento: null
          direccion: null
          barrio: null
          telefono: null
          celular: null
          correo: null
          tipo_documento_beneficiario: null
          documento_beneficiario: null
          nombre_beneficiario: null
          fecha_nacimiento: null
          parentesco: null
          ciudad_beneficiario: ''
          relacion_seguridad_social: null
          discapacidad: null
          beneficiario_eps: null
          beneficiario_caja_compensacion: null
        - usuario: Amparo Echeverry
          tipo_documento: CEDULA
          documento_usuario: '29866304'
          tipo_usuario: Administrativo
          email: 353_353_353_text@gmail.com
          negocio: Calidad de software
          empresa: Nexa Solutions
          uen: Nexa Digital Solutions
          vicepresidencia: Gestión Humana
          pais: Colombia
          ciudad: Medellin
          regional: Antioquia
          sede: Medellín
          cargo: Arquitecto TI
          nivel_organizacional: Analistas
          area: TI
          documento_jefe: '42793011'
          jefe: Deissy Echeverry Seleccion
          fecha_ingreso: 2025-06-10
          tipo_contrato: Contrato por prestación de servicios
          fecha_terminacion_contrato: null
          forma_pago: null
          tipo_salario: null
          nomina: ''
          regimen_pension: null
          tipo_cuenta: null
          banco: null
          numero_cuenta: ''
          salario: '3200000'
          cupo_beneficios: null
          centros_costos: ''
          modalidad: Casa
          labora_sabado: No
          nombres_conceptos: null
          valores_conceptos: null
          corresponde_a_salario: null
          eps: null
          pension: null
          cesantias: null
          arl: ''
          centro_trabajo_arl: ''
          porcentaje_riesgo_arl: ''
          lugar_expedicion: ABINGDON DOWNS
          fecha_expedicion_documento: 1989-01-10
          municipio_residencia: AEROGLEN
          fecha_nacimiento_colaborador: 1986-06-06
          ciudad_nacimiento: ABINGDON DOWNS
          direccion: 'Bulevar 55AD  # 66AC Este 66'
          barrio: gyyyyy
          telefono: '987564859680'
          celular: '257372572'
          correo: null
          tipo_documento_beneficiario: null
          documento_beneficiario: null
          nombre_beneficiario: null
          fecha_nacimiento: null
          parentesco: null
          ciudad_beneficiario: ''
          relacion_seguridad_social: null
          discapacidad: null
          beneficiario_eps: null
          beneficiario_caja_compensacion: null
        - usuario: Ana Maria Gomez Ramirez
          tipo_documento: CEDULA
          documento_usuario: '43609065'
          tipo_usuario: Administrativo
          email: 238_xxxisrael.fonseca@talento.cloud
          negocio: Desarrollo de Software
          empresa: talento cloud
          uen: UEN App Moviles
          vicepresidencia: financiera
          pais: Colombia
          ciudad: Medellin
          regional: Antioquia
          sede: Medellín
          cargo: Gerente de Calidad y Soporte
          nivel_organizacional: Gerencial
          area: Sistemas
          documento_jefe: '21897678'
          jefe: Blanca Ruiz Suarez
          fecha_ingreso: 2022-11-29
          tipo_contrato: Contrato a término indefinido
          fecha_terminacion_contrato: null
          forma_pago: null
          tipo_salario: null
          nomina: ''
          regimen_pension: null
          tipo_cuenta: Cuenta de ahorros
          banco: Bancolombia
          numero_cuenta: '650000005145'
          salario: null
          cupo_beneficios: null
          centros_costos: ''
          modalidad: Casa
          labora_sabado: No
          nombres_conceptos: null
          valores_conceptos: null
          corresponde_a_salario: null
          eps: COMFAMILIAR DE NARIÑO EPS - CCF
          pension: Colfondos
          cesantias: Protección S.A
          arl: ARL Positiva
          centro_trabajo_arl: ''
          porcentaje_riesgo_arl: ''
          lugar_expedicion: Ricaurte
          fecha_expedicion_documento: null
          municipio_residencia: null
          fecha_nacimiento_colaborador: null
          ciudad_nacimiento: null
          direccion: ''
          barrio: ''
          telefono: null
          celular: 3215554444xxx
          correo: null
          tipo_documento_beneficiario: null
          documento_beneficiario: null
          nombre_beneficiario: null
          fecha_nacimiento: null
          parentesco: null
          ciudad_beneficiario: ''
          relacion_seguridad_social: null
          discapacidad: null
          beneficiario_eps: null
          beneficiario_caja_compensacion: null
        success: true
    Datum:
      title: Datum
      required:
      - usuario
      - tipo_documento
      - documento_usuario
      - tipo_usuario
      - email
      - negocio
      - empresa
      - uen
      - vicepresidencia
      - pais
      - ciudad
      - regional
      - sede
      - cargo
      - nivel_organizacional
      - area
      - documento_jefe
      - jefe
      - fecha_ingreso
      - tipo_contrato
      - fecha_terminacion_contrato
      - forma_pago
      - tipo_salario
      - nomina
      - regimen_pension
      - tipo_cuenta
      - banco
      - numero_cuenta
      - salario
      - cupo_beneficios
      - centros_costos
      - modalidad
      - labora_sabado
      - nombres_conceptos
      - valores_conceptos
      - corresponde_a_salario
      - eps
      - pension
      - cesantias
      - arl
      - centro_trabajo_arl
      - porcentaje_riesgo_arl
      - lugar_expedicion
      - fecha_expedicion_documento
      - municipio_residencia
      - fecha_nacimiento_colaborador
      - ciudad_nacimiento
      - direccion
      - barrio
      - telefono
      - celular
      - correo
      - tipo_documento_beneficiario
      - documento_beneficiario
      - nombre_beneficiario
      - fecha_nacimiento
      - parentesco
      - ciudad_beneficiario
      - relacion_seguridad_social
      - discapacidad
      - beneficiario_eps
      - beneficiario_caja_compensacion
      type: object
      properties:
        usuario:
          type: string
        tipo_documento:
          type: string
        documento_usuario:
          type: string
        tipo_usuario:
          type: string
        email:
          type: string
        negocio:
          type: string
        empresa:
          type: string
        uen:
          type: string
        vicepresidencia:
          type: string
        pais:
          type: string
        ciudad:
          type: string
        regional:
          type: string
        sede:
          type: string
        cargo:
          type: string
        nivel_organizacional:
          type: string
        area:
          type: string
        documento_jefe:
          type: string
        jefe:
          type: string
        fecha_ingreso:
          type: string
        tipo_contrato:
          type: string
          nullable: true
        fecha_terminacion_contrato:
          type: string
          nullable: true
        forma_pago:
          type: string
          nullable: true
        tipo_salario:
          type: string
          nullable: true
        nomina:
          type: string
        regimen_pension:
          type: string
          nullable: true
        tipo_cuenta:
          type: string
          nullable: true
        banco:
          type: string
          nullable: true
        numero_cuenta:
          type: string
          nullable: true
        salario:
          type: string
          nullable: true
        cupo_beneficios:
          type: string
          nullable: true
        centros_costos:
          type: string
          nullable: true
        modalidad:
          type: string
          nullable: true
        labora_sabado:
          type: string
        nombres_conceptos:
          type: string
          nullable: true
        valores_conceptos:
          type: string
          nullable: true
        corresponde_a_salario:
          type: string
          nullable: true
        eps:
          type: string
          nullable: true
        pension:
          type: string
          nullable: true
        cesantias:
          type: string
          nullable: true
        arl:
          type: string
        centro_trabajo_arl:
          type: string
        porcentaje_riesgo_arl:
          type: string
        lugar_expedicion:
          type: string
          nullable: true
        fecha_expedicion_documento:
          type: string
          nullable: true
        municipio_residencia:
          type: string
          nullable: true
        fecha_nacimiento_colaborador:
          type: string
          nullable: true
        ciudad_nacimiento:
          type: string
          nullable: true
        direccion:
          type: string
          nullable: true
        barrio:
          type: string
          nullable: true
        telefono:
          type: string
          nullable: true
        celular:
          type: string
          nullable: true
        correo:
          type: string
          nullable: true
        tipo_documento_beneficiario:
          type: string
          nullable: true
        documento_beneficiario:
          type: string
          nullable: true
        nombre_beneficiario:
          type: string
          nullable: true
        fecha_nacimiento:
          type: string
          nullable: true
        parentesco:
          type: string
          nullable: true
        ciudad_beneficiario:
          type: string
        relacion_seguridad_social:
          type: string
          nullable: true
        discapacidad:
          type: string
          nullable: true
        beneficiario_eps:
          type: string
          nullable: true
        beneficiario_caja_compensacion:
          type: string
          nullable: true
      example:
        usuario: ADRIANA PEREZ PEREZCORTES
        tipo_documento: CEDULA
        documento_usuario: '8587647000'
        tipo_usuario: Administrativo
        email: basura_talpostobon790@unmail.edu
        negocio: Calidad de software
        empresa: Soluciones Estratégicas Integrales para el Desarrollo Empresarial y Tecnológico S.A.S
        uen: Nexa Digital Solutions
        vicepresidencia: Financiera
        pais: Colombia
        ciudad: Cartagena
        regional: Costa Atlántica
        sede: Cartagena
        cargo: Analista Desarrollador
        nivel_organizacional: Analistas
        area: TI
        documento_jefe: '29498498195'
        jefe: Alvaro Cardenas
        fecha_ingreso: 2026-05-12
        tipo_contrato: null
        fecha_terminacion_contrato: null
        forma_pago: null
        tipo_salario: null
        nomina: ''
        regimen_pension: null
        tipo_cuenta: null
        banco: null
        numero_cuenta: null
        salario: null
        cupo_beneficios: null
        centros_costos: null
        modalidad: null
        labora_sabado: No
        nombres_conceptos: null
        valores_conceptos: null
        corresponde_a_salario: null
        eps: null
        pension: null
        cesantias: null
        arl: ''
        centro_trabajo_arl: ''
        porcentaje_riesgo_arl: ''
        lugar_expedicion: null
        fecha_expedicion_documento: null
        municipio_residencia: null
        fecha_nacimiento_colaborador: null
        ciudad_nacimiento: null
        direccion: null
        barrio: null
        telefono: null
        celular: null
        correo: null
        tipo_documento_beneficiario: null
        documento_beneficiario: null
        nombre_beneficiario: null
        fecha_nacimiento: null
        parentesco: null
        ciudad_beneficiario: ''
        relacion_seguridad_social: null
        discapacidad: null
        beneficiario_eps: null
        beneficiario_caja_compensacion: null
    ErrorResponse:
      title: ErrorResponse
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: Token JWT inválido, expirado o ausente.    
  responses:
    UnauthorizedError:
      description: Token JWT inválido, expirado o ausente.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            success: false
            message: Token JWT inválido, expirado o ausente.
    ForbiddenError:
      description: El usuario autenticado no tiene permisos suficientes.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            success: false
            message: El usuario autenticado no tiene permisos suficientes.      
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://clientex.talento.cloud/api/html/oauth2/token/demo.json
          scopes:
            talento.read: "Permiso para leer datos de talento"
security:
- oauth2:
      - talento.read
tags:
- name: Datalake
  description: ''
